
document.addEventListener('DOMContentLoaded',()=>{if(!PCStore.cartCount()){location.href='carrito.html';return}let current=1;const form=document.getElementById('checkoutForm');function summary(){const items=PCStore.cartDetails(),t=PCStore.totals();document.getElementById('checkoutSummary').innerHTML=`<h2>Tu pedido</h2><div class="checkout-items">${items.map(i=>`<div class="checkout-mini"><img src="assets/img/${i.product.id}-main.svg" alt=""><div><strong>${i.product.name}</strong><br><small>${i.qty} × ${PCStore.formatMoney(i.product.price)}</small></div><strong>${PCStore.formatMoney(i.qty*i.product.price)}</strong></div>`).join('')}</div><div class="summary-row"><span>Subtotal</span><strong>${PCStore.formatMoney(t.sub)}</strong></div><div class="summary-row"><span>Descuento</span><strong>− ${PCStore.formatMoney(t.discount)}</strong></div><div class="summary-row"><span>Impuesto demostrativo</span><strong>${PCStore.formatMoney(t.tax)}</strong></div><div class="summary-row total"><span>Total</span><span>${PCStore.formatMoney(t.total)}</span></div><div class="secure-note"><span>🔒</span><span>Pago simulado. No se procesa dinero real.</span></div>`}summary();
 function validateStep1(){let ok=true;['fullName','email','phone','department','city'].forEach(id=>{const el=document.getElementById(id),err=el.closest('.field').querySelector('.field-error');let msg='';if(!el.value.trim())msg='Este campo es obligatorio.';if(id==='email'&&el.value&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(el.value))msg='Escribe un correo válido.';el.classList.toggle('input-error',!!msg);err.textContent=msg;if(msg)ok=false});return ok}
 function validatePayment(){const method=document.querySelector('[name=payment]:checked').value;if(method!=='Stripe Test Mode')return true;let ok=true;const vals={cardNumber:'4242424242424242',expiry:/^\d{2}\/\d{2}$/,cvv:/^\d{3}$/};['cardNumber','expiry','cvv'].forEach(id=>{const el=document.getElementById(id),v=el.value.replace(/\s/g,''),err=el.closest('.field').querySelector('.field-error');let valid=id==='cardNumber'?v===vals.cardNumber:vals[id].test(el.value);err.textContent=valid?'':'Utiliza los datos de prueba indicados.';el.classList.toggle('input-error',!valid);if(!valid)ok=false});return ok}
 function go(step){if(step===2&&current===1&&!validateStep1())return;if(step===3&&current===2&&!validatePayment())return;current=step;document.querySelectorAll('.checkout-step').forEach(s=>s.classList.toggle('active',+s.dataset.step===step));document.querySelectorAll('.progress-step').forEach(s=>{const n=+s.dataset.progress;s.classList.toggle('active',n===step);s.classList.toggle('done',n<step)});if(step===3){const method=document.querySelector('[name=payment]:checked').value;document.getElementById('reviewData').innerHTML=`<div class="legal-meta"><strong>Cliente:</strong> ${document.getElementById('fullName').value}<br><strong>Correo:</strong> ${document.getElementById('email').value}<br><strong>Teléfono:</strong> ${document.getElementById('phone').value}<br><strong>Ubicación:</strong> ${document.getElementById('city').value}, ${document.getElementById('department').value}<br><strong>Método:</strong> ${method}</div>`}if(!navigator.userAgent.includes('jsdom')){window.scrollTo({top:document.querySelector('.checkout-card').offsetTop-90,behavior:'smooth'})}}
 document.querySelectorAll('[data-next]').forEach(b=>b.onclick=()=>go(+b.dataset.next));document.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>go(+b.dataset.back));document.querySelectorAll('[name=payment]').forEach(r=>r.onchange=()=>{document.getElementById('stripeFields').classList.toggle('active',r.checked&&r.value==='Stripe Test Mode');document.getElementById('tigoFields').classList.toggle('active',r.checked&&r.value==='Tigo Money')});
 ['fullName','email','phone','department','city'].forEach(id=>document.getElementById(id).addEventListener('input',()=>{if(current===1)validateStep1()}));
 form.onsubmit=e=>{e.preventDefault();const method=document.querySelector('[name=payment]:checked').value,t=PCStore.totals(),now=new Date(),number=`HN-${now.toISOString().slice(0,10).replaceAll('-','')}-${Math.floor(1000+Math.random()*9000)}`;const order={number,date:now.toISOString(),status:method==='Tigo Money'?'Pendiente de comprobante':'Pago de prueba aprobado',method,customer:{name:document.getElementById('fullName').value,email:document.getElementById('email').value,phone:document.getElementById('phone').value,department:document.getElementById('department').value,city:document.getElementById('city').value,business:document.getElementById('businessName').value,notes:document.getElementById('deliveryNotes').value},items:PCStore.cartDetails().map(i=>({id:i.id,name:i.product.name,variant:i.variant,qty:i.qty,price:i.product.price})),totals:t};PCStore.saveOrder(order);localStorage.setItem('pcProfile',JSON.stringify({name:order.customer.name,email:order.customer.email}));PCStore.clearCart();location.href='confirmacion.html'};
});
